id = "arc-dark-theme"
name = "Arc Dark Theme"
version = "0.1.0"
schema_version = 1
authors = ["Will Cygan <wcygan.io@gmail.com>"]
description = "Arc Dark theme for Zed based on the popular Arc Dark color scheme"
repository = "https://github.com/wcygan/zed-arc-dark-theme"
